# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileSave.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgFileSave(object):
    def setupUi(self, dlgFileSave):
        dlgFileSave.setObjectName("dlgFileSave")
        dlgFileSave.resize(350, 130)
        self.dlgbxFileSave = QtWidgets.QDialogButtonBox(dlgFileSave)
        self.dlgbxFileSave.setGeometry(QtCore.QRect(70, 80, 261, 32))
        font = QtGui.QFont()
        font.setFamily("Piboto [Goog]")
        font.setPointSize(10)
        self.dlgbxFileSave.setFont(font)
        self.dlgbxFileSave.setOrientation(QtCore.Qt.Horizontal)
        self.dlgbxFileSave.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dlgbxFileSave.setObjectName("dlgbxFileSave")
        self.cbxFileList = QtWidgets.QComboBox(dlgFileSave)
        self.cbxFileList.setGeometry(QtCore.QRect(100, 30, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Piboto [Goog]")
        font.setPointSize(10)
        self.cbxFileList.setFont(font)
        self.cbxFileList.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.cbxFileList.setObjectName("cbxFileList")
        self.label = QtWidgets.QLabel(dlgFileSave)
        self.label.setGeometry(QtCore.QRect(20, 30, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Piboto [Goog]")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.retranslateUi(dlgFileSave)
        dlgFileSave.accepted.connect(dlgFileSave.accept)
        dlgFileSave.rejected.connect(dlgFileSave.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgFileSave)

    def retranslateUi(self, dlgFileSave):
        _translate = QtCore.QCoreApplication.translate
        dlgFileSave.setWindowTitle(_translate("dlgFileSave", "File Save"))
        self.label.setText(_translate("dlgFileSave", "Select File:"))
